name: loci
description: App Cardápio.



publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  numberpicker: ^2.1.1
  tab_indicator_styler: ^1.0.0
  flutter_credit_card: ^0.1.4
  slimy_card: ^1.0.4
  flutter_svg: ^0.19.3
  flutter_fluid_slider: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true
